# Site settings
title: Tiger & Dormouse
email: vicapa99@gmail.com
author: Pablo Vicente
description: >
  Thoughts of a mountain based software developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pvcarrera.github.com"
twitter_username: pvcarrera
github_username:  pvcarrera

# Build settings
markdown: kramdown
